# prefix key highlight
set -g status-style 'bg=colour235 fg=colour136'
set -g message-style 'bg=colour136 fg=colour235'

# prefix が押されたときステータスバーを黄色に
set -g status-left '#[fg=colour235,bg=colour136]#{?client_prefix, PREFIX ,}#[default] '

# ウィンドウタイトル
set -g window-status-current-style 'bg=colour136 fg=colour235 bold'

# マウス有効
set -g mouse on

# ウィンドウ番号を1始まりに
set -g base-index 1
set -g pane-base-index 1

# 256色
set -g default-terminal "screen-256color"
